// <auto-generated />
namespace Schedule.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addnotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201307060111543_add-notes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
