// <auto-generated />
namespace Schedule.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class renamed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamed));
        
        string IMigrationMetadata.Id
        {
            get { return "201307072222329_renamed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
